### PR TITLE
Input transformer for CloudWatch / EventBridge events

### PR DESCRIPTION
**Pull request by zirkelc**
This PR adds the InputTransformer to CloudWatch and EventBridge events for issue #102 

- README updated
- Test case added
- Example serverless project added and deployed

### CODE REVIEW

**Comment by horike37** [comment]
@chriszirkel 
Sorry for my delayed response. This is a great improvement! Thanks😊 

Why have you put the example directory? I understand what it means. However, it needs more examples other than this  PR if the directory is created, like covering almost all use cases of this plugin.

And can you fix the conflict?

**Comment by chriszirkel** [comment]
@horike37 the example directory was just for me to test it directly - I didn't mean to commit it. 
I removed this directory and restored the package-lock.json from master.

**Comment by bayoudhi** [comment]
Hi @zirkelc any updates on this? 🙂

**Comment by zirkelc** [comment]
> Hi @zirkelc any updates on this? It would be great if we can add this feature 🙂

I wasn't aware that there's an open issue that must be solved. I fixed the merge conflict, hope this PR is now ready to be merged :-)

**Comment by horike37** [comment]
@zirkelc 
Thanks! It's perfect! This will be merged and shipped soon.

**Pull request merged**
