### PR TITLE
feat: add ExecutionSucceeded as a valid metric

### PR DESCRIPTION
**Pull request by vbhavsar**
Fixes https://github.com/serverless-operations/serverless-step-functions/issues/376

### CODE REVIEW

**Review by theburningmonk — APPROVED** [review]

**Comment by vbhavsar** [comment]
Thanks @theburningmonk!

**Comment by theburningmonk** [comment]
No probs. I'm curious though, what's the use case for alerting on success?

**Comment by vbhavsar** [comment]
We want to inform teams that a step function executed successfully. In one case, the person on-call needs to restart a service to use the database that the step function finished creating.

**Comment by theburningmonk** [comment]
Ok, gotcha 👍

**Pull request merged**
