### PR TITLE
Generating random variable names for intrinsic functions breaks Serverless caching

### PR DESCRIPTION
**Pull request by FilipPyrek**
This PR solves #299

### CODE REVIEW

**Comment by theburningmonk** [comment]
@FilipPyrek thanks for the PR, is this ready for review?

**Comment by theburningmonk** [comment]
@FilipPyrek no probs, thank you 👍

**Comment by FilipPyrek** [comment]
Ready for review @theburningmonk 👍

**Comment by theburningmonk** [comment]
@FilipPyrek sorry, got distracted with other things and didn't get around to reviewing until now

**Pull request merged**
