### PR TITLE
Allow logging to standard workflow

### PR DESCRIPTION
**Pull request by deconltd**
Currently, logging is available only for express workflows. this pull request enables it for standard workflows as well

### CODE REVIEW

**Comment by theburningmonk** [comment]
thanks @deconltd can you add a quick test for this?

**Comment by deconltd** [comment]
@theburningmonk done

**Comment by taschmidt** [comment]
Is this ready to get merged and released?

**Comment by horike37** [comment]
@deconltd 
Thank you for your contribution. I personally need this feature for my work 👍 
Great.

@taschmidt 
Sorry for waiting for you. This will be shipped right now.

**Pull request merged**
