### PR TITLE
feat: allow Fn::ImportValue for alarm topics

### PR DESCRIPTION
**Pull request by Luke-Davies**
The same as #263 but for alarm topics.

```
      alarms:
        topics:
          ok:
            Fn::ImportValue: my-alarm-topic
          alarm:
            Fn::ImportValue: my-alarm-topic
        metrics:
          - executionsTimedOut
          - executionsFailed
          - executionsAborted
```

### CODE REVIEW

**Comment by Luke-Davies** [comment]
Thanks for the review @theburningmonk.
Any chance of a patch release for this?

**Comment by ThrowingSpoon** [comment]
@theburningmonk Bumping as I could really use this in a release please.

**Comment by theburningmonk** [comment]
@ThrowingSpoon this has been released now but I haven't had a chance to test it out myself, so please let me know if there's any issues when you try it out.

**Pull request merged**
