### PR TITLE
Full cors object support

### PR DESCRIPTION
**Pull request by wolfgz**
```yaml
stepFunctions:
  stateMachines:
    peopleReport:
      name: ${self:custom.service_base}-${self:custom.stage}-test
      events:
        - http:
            path: test
            method: POST
            action: StartExecution
            cors:
              allowCredentials: true
              origin: https://test.site.com
              headers: [test]
              methods: ANY
```

yields (only the affected IntegrationResponses and MethodResponses are shown)
```json
{
  "IntegrationResponses": [
    {
      "StatusCode": 200,
      "SelectionPattern": 200,
      "ResponseParameters": {
        "method.response.header.Access-Control-Allow-Origin": "'https://test.site.com'",
        "method.response.header.Access-Control-Allow-Headers": "'test'",
        "method.response.header.Access-Control-Allow-Methods": "'DELETE,GET,HEAD,PATCH,POST,PUT,OPTIONS,POST'",
        "method.response.header.Access-Control-Allow-Credentials": "'true'"
      },
      "ResponseTemplates": {}
    },
    {
      "StatusCode": 400,
      "SelectionPattern": 400,
      "ResponseParameters": {
        "method.response.header.Access-Control-Allow-Origin": "'https://test.site.com'",
        "method.response.header.Access-Control-Allow-Headers": "'test'",
        "method.response.header.Access-Control-Allow-Methods": "'DELETE,GET,HEAD,PATCH,POST,PUT,OPTIONS,POST'",
        "method.response.header.Access-Control-Allow-Credentials": "'true'"
      },
      "ResponseTemplates": {}
    }
  ]
  },
  "MethodResponses": [
  {
    "ResponseParameters": {
      "method.response.header.Access-Control-Allow-Origin": true,
      "method.response.header.Access-Control-Allow-Headers": true,
      "method.response.header.Access-Control-Allow-Methods": true,
      "method.response.header.Access-Control-Allow-Credentials": true
    },
    "ResponseModels": {},
    "StatusCode": 200
  },
  {
    "ResponseParameters": {
      "method.response.header.Access-Control-Allow-Origin": true,
      "method.response.header.Access-Control-Allow-Headers": true,
      "method.response.header.Access-Control-Allow-Methods": true,
      "method.response.header.Access-Control-Allow-Credentials": true
    },
    "ResponseModels": {},
    "StatusCode": 400
  }
  ]
}
```

### CODE REVIEW

**Comment by wolfgz** [comment]
rerunning linting now.
regarding the failed test, can someone please confirm whether or not the test is valid? Per CloudFormation docs the value should be a boolean. I believe the test should be comparing a truthy value instead of the actual value as that seems to be done in the getMethodIntegration and the getIntegrationResponse seemed to be copy-pasted. In my PR there is a correction for the test as well.
- [Integration Response](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apitgateway-method-integration-integrationresponse.html#cfn-apigateway-method-integration-integrationresponse-responseparameters)
- [Method Response](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apitgateway-method-methodresponse.html#cfn-apigateway-method-methodresponse-responseparameters)

**Comment by wolfgz** [comment]
Looking for a bugfix patch to be released if this is accepted.
@theburningmonk

**Comment by osbornea** [comment]
Looking forward to using this if @theburningmonk  or @horike37 can give an update when this might be released that would be helpful

**Comment by theburningmonk** [comment]
@wolfgz the change looks good, have you tested it out on a project yet? (like replacing the relevant files in your `node_modules` and then run `sls deploy` to see if it actually does what you expect)

Also, can you add an example or two to the `README`?

**Pull request closed without merging**
