### PR TITLE
feat: generate permission for dynamodb:Query and for GSIs

### PR DESCRIPTION
**Pull request by bahrmichael**
This PR adds support to generate IAM statements for `dynamodb:Query`.

Currently I get this error:

```
Cannot generate IAM policy statement for Task state { Type: 'Task',
  Parameters:
   { TableName: { Ref: 'OrdersTable' },
     IndexName: 'GSI1',
     KeyConditionExpression: 'gsi1 = :k',
     FilterExpression: '$.listMatchableOrdersFilter',
     ExpressionAttributeValues: { ':k': { 'S.$': '$.listMatchableOrdersKey' }, ':p': { 'N.$': '$.newOrder.pricePerUnit' } } },
  Resource: 'arn:aws:states:::aws-sdk:dynamodb:query',
  Next: 'Is Empty?',
  ResultPath: '$.matchableOrders' }
```

With this PR it should be able to generate a statement that supports the Query operation, and also supports GSIs. I went with a wildcard `*` index following the table related code above. If the index name is only known at runtime, there's no way we can grant any correct permission that's not a `*` index.

If the `Parameters` contain neither `IndexName.$` nor `IndexName`, then the changed code will return the table name as before this PR.

### CODE REVIEW

**Comment by lopburny** [comment]
@bahrmichael Thank you for this PR👍 Looks good to me. Could you add a test case for this?

**Comment by jordan-badger** [comment]
@bahrmichael nice work. I had the same issue so found this PR.  I have just tested this out and came across a tiny bug that is the table ARN is a string when I think it should be an ARN object, My fix was

`function getDynamoDBPermissions(action, state) {
  let tableArn = state.Parameters['TableName.$']
    ? '*'
    : getDynamoDBArn(state.Parameters.TableName);

  const indexName = state.Parameters['IndexName.$']
    ? state.Parameters['IndexName.$']
    : state.Parameters['IndexName'];

  if (indexName && tableArn !== '*') {
    tableArn = getDynamoDBArn(`${state.Parameters.TableName}/index/${indexName}`)
  }

  return [{
    action,
    resource: tableArn,
  }];
}`

**Comment by bahrmichael** [comment]
Thank you @jordan-badger! I'm making slow progress on the unit tests.

**Comment by jordan-badger** [comment]
@bahrmichael not sure if this will be any assistance but I wrote this for a index permission test for my changes locally:

```
it('should give dynamodb permission to index table whenever IndexName is provided', () => {
    const helloTable = 'hello';

    const genStateMachine = (id, tableName) => ({
      id,
      definition: {
        StartAt: 'A',
        States: {
          A: {
            Type: 'Task',
            Resource: 'arn:aws:states:::aws-sdk:dynamodb:query',
            Parameters: {
              TableName: tableName
            },
            Next: 'B',
          },
          B: {
            Type: 'Task',
            Resource: 'arn:aws:states:::aws-sdk:dynamodb:query',
            Parameters: {
              TableName: tableName,
              IndexName: "GSI1"
            },
            End: true,
          },
        },
      },
    });

    serverless.service.stepFunctions = {
      stateMachines: {
        myStateMachine1: genStateMachine('StateMachine1', helloTable),
      },
    };

    serverlessStepFunctions.compileIamRole();
    const policy = serverlessStepFunctions.serverless.service
      .provider.compiledCloudFormationTemplate.Resources.StateMachine1Role
      .Properties.Policies[0];

    expect(policy.PolicyDocument.Statement[0].Action)
      .to.be.deep.equal(['dynamodb:query']);

    expect(policy.PolicyDocument.Statement[0].Resource[0]).to.be.deep.equal({
      "Fn::Join": [":", ["arn", {"Ref": "AWS::Partition"}, "dynamodb", {"Ref": "AWS::Region"}, {"Ref": "AWS::AccountId"}, "table/hello"]]
    });

    expect(policy.PolicyDocument.Statement[0].Resource[1]).to.be.deep.equal({
      "Fn::Join": [":", ["arn", {"Ref": "AWS::Partition"}, "dynamodb", {"Ref": "AWS::Region"}, {"Ref": "AWS::AccountId"}, "table/hello/index/GSI1"]]
    });
  });
```

**Comment by bahrmichael** [comment]
@jordan-badger I worked your test and fix into the code, and added a few comments to clarify my understanding of the code.

@lopburny I think we're ready to move forward. Would you mind taking another look if you discover more test cases that we should tackle?

**Comment by lopburny** [comment]
@bahrmichael @jordan-badger Thank you so much folks, all looks good to me👍

**Pull request merged**
