### PR TITLE
add vpcEndpointIds to EndpointConfiguration

### PR DESCRIPTION
**Pull request by raphaeldeem-acorns**
Fixes: https://github.com/serverless-operations/serverless-step-functions/issues/523

### CODE REVIEW

**Comment by raphaeldeem-acorns** [comment]
@lopburny

**Comment by raphaeldeem-acorns** [comment]
@lopburny can you please approve the workflow for this?

**Comment by raphaeldeem-acorns** [comment]
@horike37 are you able to approve the workflow for this, or review it?

**Comment by raphaeldeem-acorns** [comment]
@lopburny thanks, I fixed the linting errors! Could you have another look please have you get a chance?

**Comment by lopburny** [comment]
@raphaeldeem-acorns looks good to me!

**Pull request merged**
