### PR TITLE
Create Schedules using Eventbridge Scheduler

### LINKED ISSUE #571: EventBridge Scheduler Integration for Stepfunction
# Feature Proposal

For feature proposals:
-> Ability to create AWS::Scheduler::Schedule triggers as an alternative to AWS::Event::Rule, which may be preferable if hitting account-wide limits on a number of AWS::Event::Rule triggers per bus (Lambdas are only able to be triggered from the default bus).
-> Also, specify a timezone to run it on local time.

### PR DESCRIPTION
**Pull request by KillDozerX2**
Fixes #571

### CODE REVIEW

**Comment by jappurohit041** [comment]
Hii @horike37 @lopburny,

Could we please have look at this PR, as it has been opened since very long and it is kind of important to make it in sync with Serverless https://github.com/serverless/serverless/pull/11935 ?

Thanks

**Comment by horike37** [comment]
@jappurohit041 
Thank you for this PR. Looks good to me, seeing the added code and test that checks if the required parameters are given from serverless.yml.

Have you done actual tests for this feature? I mean like if this feature doesn't introduce any side effects to existing features, or if this keeps backward compatibility. Because I couldn't have enough time to check it.

If so, I will merge this PR and release it after you fix some linting errors.

**Comment by jappurohit041** [comment]
Hii @horike37,

I have fixed lint issue, and due to the distinct logical ID, two test failed, so fixed the test case.

Also, I have done the actual tests for this feature, after the latest commit, and it is not breaking.

Working as expected😄

**Pull request merged**
