### PR TITLE
feat: add request validator schema for http events

### LINKED ISSUE #554: Add request schema to an http event for the stepfunction for validation
# This is a Feature Proposal

## Description

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

It would be useful to have the possibility to add a request schema to a http event for the statemachine similar how you would add it for a function. This way, none valid input will be rejected before it hits the statemachine and there is no invocation which reduces cost.

* If there is additional config how would it look

I tried to add the event schema to my statemachine which did not result in any error, however no model was created in the apigateway. The generated `serverless-state.json` looked like this:

```
"stateMachines": {
          "mystatemachine": {
            "id": "mystatemachine",
            "events": [
              {
                "http": {
                  "path": "start",
                  "method": "post",
                  "private": true,
                  "request": {
                    "schemas": {
                      "application/json": {
                        "type": "object",
                        "properties": {
                          "Input": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "Input"
                        ]
                      }
                    }
                  }
                }
              }
```

In comparison a similar request schema for a function looks like this:

```

"functions": {
      "hello": {
        "handler": "src/functions/hello/handler.main",
        "events": [
          {
            "http": {
              "method": "post",
              "path": "hello",
              "request": {
                "schemas": {
                  "application/json": {
                    "$ref": "$[\"service\"][\"provider\"][\"compiledCloudFormationTemplate\"][\"Resources\"][\"ApiGatewayMethodHelloPostApplicationJsonModel\"][\"Properties\"][\"Schema\"]"
                  }
                }
              },
              "integration": "AWS_PROXY"
            }
          }
```

### PR DESCRIPTION
**Pull request by paolorossig**
It adds support for http request validators, same behavior as for functions http events.

The serverless definition is as follows:

```
stepFunctions:
  stateMachines:
    First:
      events:
        - http:
            path: path/to
            method: POST
            request:
              schemas:
                application/json: start-execution
                  name:  TestSchema
                  schema: ${file(schema.json)}
      definition:
        StartAt: Test
        States:
          ...
    
```

Closes #554

### CODE REVIEW

**Comment by horike37** [comment]
@paolorossig 
Thank you for this PR. Looks good so far. And as the rest of the tasks, we have to write documentation.
Would you add an explanation of this feature in the Readme so that people know how to use this?

**Comment by paolorossig** [comment]
@horike37 You are welcome! I just updated the README with the feature explanation of request validators with some examples.

**Comment by paolorossig** [comment]
@horike37 did you have a chance to review the missing documentation of this pr?

**Comment by horike37** [comment]
@paolorossig 
Sorry for being late. LGTM!

**Pull request merged**
