### PR TITLE
Upgrade to new Serverless Framework variables resolver

### LINKED ISSUE #446: New ${aws:xxx} variables added in serverless 2.50.0 and this plugin breaks packaging / deployment
minimal example to reproduce

```
service:
  name: aws-region-variable-test
plugins:
  - serverless-step-functions
provider:
  name: aws
  region: us-east-1
functions:
  example:
    handler: src/test.handler
    environment:
      AWS_REGION_TEST: ${aws:region}
      AWS_ACCOUNTID_TEST: ${aws:region}
```

```
$ sls package
Serverless Error ----------------------------------------
 
  Invalid variable reference syntax for variable aws:region. You can only reference env vars, options, & files. You can check our docs for more info.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.15.4
     Framework Version:         2.50.0
     Plugin Version:            5.4.3
     SDK Version:               4.2.3
     Components Version:        3.13.3

```

commenting  serverless-step-functions results in packaging or deployment success

### PR DESCRIPTION
**Pull request by medikoo**
Fixes #446 
Fixes https://github.com/serverless-operations/serverless-step-functions/issues/439

Breaking change, as this drops support for old variables resolver, sp effectively drops support for version of Framework below v2.32.0 (reflected that by registering `serverless` as peer dependency).

Additionally upgraded internal tests so they work with v2 version of a Framework.

After this is merged, I believe ideally v3.0.0 needs to be released.

Having that done, it'll be nice to create a maintenance release for v2 branch where `serverless` is registered as peer dependency but with support for `>=1 <2.32` (once `v2` branch is setup I'll be happy to also prepare PR for that)

### CODE REVIEW

**Comment by horike37** [comment]
@medikoo 
Thanks! I will take a look at this PR.

**Comment by medikoo** [comment]
Great thanks @horike37 !

**Review by horike37 — APPROVED** [review]
@medikoo 
I tested and checked your PR and looks good from my perspective!
After merging, I will prepare to release `v3`

**Comment by medikoo** [comment]
@horike37 great thanks for publishing this!

**Pull request merged**
